### ISSUE TITLE
Error on java.lang.NoSuchMethodError: TreeNode.setChildren

### ISSUE THREAD

**Issue by aszx4510** [SAG-KeLP/kelp-input-generator#2]
I execute the example code. 

```
public void generateGRCT() {
	// Instantiate a new DependencyParser, i.e., a StanfordParser
	DependencyParser parser = new StanfordParserWrapper();
	parser.initialize();
	// Initialize the label generators for: syntactic nodes, lexical nodes and part-of-speech nodes
	SyntElementLabelGenerator rg = new RelationNameLabelGenerator();
	LexicalElementLabelGenerator ng = new LemmaCompactPOSLabelGeneratorLowerCase();
	PosElementLabelGenerator ig = new OriginalPOSLabelGenerator();

	// Parser a sentence
	DependencyGraph parse = parser.parse("The cat runs over the grass.");

	// Generate the KeLP TreeRepresentation
	TreeRepresentation grctGenerator1 = TreeRepresentationGenerator.grctGenerator(parse, rg, ng, ig);
	String grct1 = grctGenerator1.getTextFromData();
	System.out.println(grct1.replace("(", "[").replace(")", "]"));
}
```

Here is the bug information.
```
Exception in thread "main" java.lang.NoSuchMethodError: it.uniroma2.sag.kelp.data.representation.tree.node.TreeNode.setChildren(Ljava/util/ArrayList;)V
	at it.uniroma2.sag.kelp.input.tree.TreeRepresentationGenerator.generateGrctRepresentation(TreeRepresentationGenerator.java:63)
	at it.uniroma2.sag.kelp.input.tree.TreeRepresentationGenerator.generateGrctRepresentation(TreeRepresentationGenerator.java:90)
	at it.uniroma2.sag.kelp.input.tree.TreeRepresentationGenerator.generateGrctRepresentation(TreeRepresentationGenerator.java:90)
	at it.uniroma2.sag.kelp.input.tree.TreeRepresentationGenerator.grctGenerator(TreeRepresentationGenerator.java:48)
	at tw.edu.sinica.iis.iasl.PoliticalTreeExperiment.Test.generateGRCT(Test.java:60)
	at tw.edu.sinica.iis.iasl.PoliticalTreeExperiment.Test.main(Test.java:43)
```

Maybe there is a new version of TreeNode.java?

Thanks in advance
Wind

**Comment by crux82** [comment]
Dear Wind, 

which KeLP versione are you using?
Up now, you should use the 2.2.1-SNAPSHOT.

Best regards

Danilo

**Comment by aszx4510** [comment]
I solved this problem.
Since this [issue](https://github.com/SAG-KeLP/kelp-full/issues/5), I already use 2.2.1-SNAPSHOT for kelp-full.
I downloaded jar files of 2.2.1-SNAPSHOT by Maven at 2017-05-12. There are old jar files in the .m2 directory.
But this project, kelp-input-generator, need the latest version [TreeNode.java
](https://github.com/SAG-KeLP/kelp-additional-kernels/blob/master/src/main/java/it/uniroma2/sag/kelp/data/representation/tree/node/TreeNode.java)
I delete the old jar files of "kelp-additional-kernels" and download it again.
Now I get the latest version 2.2.1-SNAPSHOT and the example code works well.

Maybe you can release a new version of kelp-full? :laughing: 
Sorry about my bad English.


Best regards
Wind

**Comment by crux82** [comment]
Dear Wind, 

we are planning to release a new version of KeLP in the next days.
Stay tunes and, most importantly, thank you for using KeLP :-)

Best regards

Danilo
